# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    siteUrl: 'http://127.0.0.1:8000/api'
    security_token: '%env(resolve:SECURITY_TOKEN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#     Application\:
#         resource: '../src/'
#         exclude:
#             - '../src/DependencyInjection/'
#             - '../src/Entity/'
#             - '../src/Kernel.php'
#             - '../src/Tests/'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\ArticleAPI\Http\Controller\:
        resource: '../src/ArticleAPI/Http/Controller/'
        tags: ['controller.service_arguments']

    ## Fixtures
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

imports:
    - { resource: "../src/ArticleAPI/Resources/config/services.yaml"}
    - { resource: "../vendor/nelmio/api-doc-bundle/Resources/config/services.xml"}